version: '3.5'

services:
  mssql:
    container_name: mssql_container_ubuntu
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "MsProject@2022"
      ACCEPT_EULA: "Y"
      TZ: "America/Sao_Paulo"
    volumes:
      - ms-project-main-db:/var/opt/mssql/data
    ports:
      - "1433:1433"
    networks:
      - ms-project-main
    restart: unless-stopped

networks:
  ms-project-main:
    driver: bridge

volumes:
  ms-project-main-db:

    
